### ISSUE TITLE
HTTPError: HTTP Error 400: DBSMigration:  ENQUEUEING_FAILED.

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4335]
The publication for some files is failing for this error. @belforte any hints?

**Comment by juztas** [comment]
For other dataset this happened also :
/JetHT/StoreResults-Run2012B_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1/USER
https://cmsweb.cern.ch/das/request?view=list&limit=10&instance=prod%2Fglobal&input=dataset%3D%2FJetHT%2FStoreResults-Run2012B_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1%2FUSER
http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=997168
```
2015-02-10 03:02:30,528:DEBUG:PublisherWorker:Submit migration from source DBS https://cmsweb.cern.ch/dbs/prod/global/DBSReader to destination https://cmsweb.cern.ch/dbs/pro
d/phys03/DBSMigrate.
2015-02-10 03:02:31,052:DEBUG:PublisherWorker:Dataset /JetHT/StoreResults-Run2012B_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1/USER must be migrated; not in the 
destination DBS.
2015-02-10 03:02:31,052:DEBUG:PublisherWorker:About to submit migrate request for {'migration_input': '/JetHT/StoreResults-Run2012B_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb5
25b618345b5-v1/USER', 'migration_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader'}
2015-02-10 03:02:32,130:ERROR:PublisherWorker:Request to migrate /JetHT/StoreResults-Run2012B_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1/USER failed.
Traceback (most recent call last):
  File "/data/srv/asyncstageout/v1.0.3pre5/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre5/lib/python2.6/site-packages/AsyncStageOut/PublisherWorker.py", line 533
, in migrateDBS3
    result = migrateApi.submitMigration(data)
  File "/data/srv/asyncstageout/v1.0.3pre5/sw.pre.riahi/slc6_amd64_gcc481/cms/dbs3-client/3.2.7b/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 1096, in submitMigration
    return self.__callServer("submit", data=migrationObj, callmethod='POST')
  File "/data/srv/asyncstageout/v1.0.3pre5/sw.pre.riahi/slc6_amd64_gcc481/cms/dbs3-client/3.2.7b/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 166, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/asyncstageout/v1.0.3pre5/sw.pre.riahi/slc6_amd64_gcc481/cms/dbs3-client/3.2.7b/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 194, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 400: DBSMigration:  ENQUEUEING_FAILED.
2015-02-10 03:02:32,131:INFO:PublisherWorker:Failed to migrate /JetHT/StoreResults-Run2012B_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1/USER from https://cmsweb.cern.ch/dbs/prod/global/DBSReader to https://cmsweb.cern.ch/dbs/prod/phys03/DBSMigrate; not publishing any files.
```

**Comment by belforte** [comment]
we need to understand. If really a dataset is missing needed metadata it indicated two bugs:
in the code which published, and in the DBS server which accepted 
I did not follow up on Hassen's comment on Dec 15, but were DBS experts contacted ?

**Comment by HassenRiahi** [comment]
The metadata is missed for the published dataset in the local DBS. When looking to the metadata there is no "Creation time: 2014-11-14 10:01:33, Dataset size: 1.2TB, Number of blocks: 5, Number of events: 14580808, Number of files: 362..." https://cmsweb.cern.ch/das/request?view=list&limit=10&instance=prod%2Fphys03&input=dataset%3D%2FJetHT%2FStoreResults-Run2012B_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1%2FUSER. Maybe it is the reason for which the migration of the dataset to the local DBS from ASO gave this problem.  
The problem could be reproduced by running this script ( * ). 

( * )

import logging
import dbs.apis.dbsClient as dbsClient
import os

proxy = os.environ.get("SOCKS5_PROXY")
migrateURL="https://cmsweb.cern.ch/dbs/prod/phys03/DBSMigrate"
migrateApi = dbsClient.DbsApi(url=migrateURL, proxy=proxy)
data = {'migration_input': '/JetHT/StoreResults-Run2012D_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1/USER', 'migration_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader/'}
result = migrateApi.submitMigration(data)
status = migrateApi.statusMigration(dataset='/JetHT/StoreResults-Run2012B_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1/USER')
print status

**Comment by HassenRiahi** [comment]
The publication in ASO should not stay idle forever in this case but it should fail reporting back the error. https://github.com/dmwm/AsyncStageout/issues/4372 .

**Comment by belforte** [comment]
@HassenRiahi Do I understand correctly that  you try to migrate from global to phys03 and say that it fails because dataset is already in phys03 but with incomplete metadata ? Or is the dataset information uncomplete in global ?
Did you ever report to DBS developers ?
